"""Add Movies and Genres tables

Revision ID: 0543ba528003
Revises: 4c23dd5c88e7
Create Date: 2024-08-09 11:49:26.878743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '0543ba528003'
down_revision: Union[str, None] = '4c23dd5c88e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Genres',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('genre_id')
    )
    op.create_table('Movies',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('overview', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('poster_path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('backdrop_path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Integer(), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('vote_average', sa.Float(), nullable=True),
    sa.Column('vote_count', sa.Integer(), nullable=True),
    sa.Column('tagline', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('adult', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('movie_id')
    )
    op.add_column('MovieUsers', sa.Column('saved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MovieUsers', 'saved')
    op.drop_table('Movies')
    op.drop_table('Genres')
    # ### end Alembic commands ###
